import os

AMOUNT_DECIMAL_PRECISION = int(os.getenv("AMOUNT_DECIMAL_PRECISION", 2))

# Offer types.
SECOND_UNIT_PERCENT_DISCOUNT = "SECOND_UNIT_PERCENT_DISCOUNT"
FLAT_DISCOUNT = "FLAT_DISCOUNT"
PERCENT_DISCOUNT = "PERCENT_DISCOUNT"
